### ISSUE TITLE
protector_drop when lag exists allows getting copy of item if item is instant-dig

### ISSUE THREAD

**Issue by expertmm** [tenplus1/protector#19]
To create lag:
* install mobs_sky
* add around 3 world anchors in various parts of the map
* wait several hours
* when you log back on, there will be hundreds or thousands of bird depending on how long you waited
* you may also need around 12 people logged into the server and not be using redis (redis is probably too fast for this test)

To test duplication:
* add the line ```protector_drop = true``` in minetest.conf in your subgame folder
* Log in and and create a protection block
* Log in as alternate player and give yourself technic:mining_drill_mk3 
* break a protected block with it, then pick up the mining drill quickly

**Comment by tenplus1** [comment]
Protector_drop removed from mod.
