### ISSUE TITLE
Conflicts with new HUD feature

### ISSUE THREAD

**Issue by aerozoic** [tenplus1/protector#23]
In https://github.com/tenplus1/protector/commit/974a024171529ec14d08e5d6b87bb995627a978f "you can build here" is displayed within the protected static spawnpoint radius. It is also displayed within protected areas of other protection mods like [areas]. 
:large_orange_diamond:

**Comment by tenplus1** [comment]
removed "you can build here" and left it blank, will show name of owner protectors nearby and it's up to areas to display own areas in hud.
