### ISSUE TITLE
pointed_thing.above doesn't always return the actual "candidate position"

### ISSUE THREAD

**Issue by est31** [tenplus1/protector#3]
In [this code](https://github.com/tenplus1/protector/blob/d069046c2ea1905237791b81b6e0a8f3ecb66d33/init.lua#L187), you use `pointed_thing.above` to determine the "candidate position" the node gets placed to. But in the case `pointed_thing.under` is buildable_to, [`pointed_thing.under` is chosen instead](https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L224-228). In this case, this can lead to players being able to place protector nodes that overlap with other protector nodes by one. This fortunately doesn't enable the player who placed the overlapping protector to dig nodes inside that area, but the owner can't dig there either.

The fix would be to just copy the code, but it isn't very satisfactory.

I'll try to extend the minetest API for nodedefs with a can_dig callback, so that this callback can be used instead, this is a more satisfactory solution for the problem.

**Comment by est31** [comment]
Also note that its better to overwrite the `on_place` callback in the nodedef than overwriting `minetest.item_place`. If every mod would do this, load on placing any item would increase linearly, if every mod overwrites the nodedef's callback, load increases logarithmically.

**Comment by tenplus1** [comment]
used on_place now :) works fine.
